name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # or your working branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Site
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # deploy root directory (can be 'dist' or 'build' if using a bundler)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
